---
- name: Set {{ prometheus_software_name_version }} ({{ installer_instance.name }} instance) facts
  set_fact:
    prometheus_software_extra_opts: '{{ installer_instance.extra_opts | default("") }}'
    prometheus_software_service_name: '{{ prometheus_software_name }}__{{ installer_instance.name }}'
    prometheus_software_instance_port: '{{ installer_instance.port | default(prometheus_software_port) }}'
    prometheus_software_config: '{{ installer_instance.data | from_yaml }}'
    prometheus_software_config_file: '{{ prometheus_etc_dir }}/{{ prometheus_software_name }}.{{ installer_instance.name }}.yml'
    prometheus_software_config_name: '{{ prometheus_software_name }}.{{ installer_instance.name }}.yml'
    prometheus_software_runas: '{{ installer_instance.user }}'
    prometheus_software_filename: '{{ prometheus_software_name }}_{{ prometheus_software_version }}_{{ prometheus_architecture | replace("-", "_") }}.tar.gz'
    prometheus_software_bin_url: 'https://github.com/ncabatoff/{{ prometheus_software_name }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_name }}_{{ prometheus_software_version }}_{{ prometheus_architecture | replace("-", "_") }}.tar.gz'
    prometheus_software_opts: '{{ lookup("template", "../vars/instances/" + prometheus_software_name + "-opts.yml")|from_yaml }}'

- name: Include task to perform {{ prometheus_software_name_version }} ({{ installer_instance.name }} instance) fact definitions
  include_tasks: _install_facts.yml

- name: 'Setup {{ prometheus_software_name_version }} ({{ installer_instance.name }}) configuration file ({{ prometheus_etc_dir }}/{{ prometheus_software_name }}.{{ installer_instance.name }}.yml)'
  become: true
  template:
    src: '../templates/generic-config.yml.j2'
    dest: '{{ prometheus_software_config_file }}'
    owner: root
    group: root
    mode: 0644
    backup: true
  register: prometheus_software_cfg

- name: Include task to setup {{ prometheus_software_name_version }} ({{ installer_instance.name }}) service
  include_tasks: _service.yml
