---
- name: 'Set {{ prometheus_software_name_version }} installation core facts'
  set_fact:
    prometheus_software_command_args: '{{ prometheus_software_opts }} + {{ prometheus_software_extra_opts | default([], true) }}'
    prometheus_software_root_dir: '{% if prometheus_exporter is defined and not prometheus_exporter %}{{ prometheus_root_dir }}/{{ prometheus_software_name }}{% else %}{{ prometheus_exporters_dir }}/{{ prometheus_software_name }}{% endif %}'
    prometheus_software_service_name: '{{ prometheus_software_service_name | default(prometheus_software_name, true) }}'
    # The shortname is the software's internal name. The author's name if added as a suffix
    # in some cases, the shortname never includes the author suffix
    prometheus_software_shortname: '{{ prometheus_software_shortname | default(prometheus_software_name) }}'
    prometheus_software_src_dir: '{{ prometheus_tmp_dir }}/{{ prometheus_software_name }}-{{ prometheus_software_version }}{{ prometheus_software_src_dir_suffix }}'
