---
- name: Include task to perform {{ prometheus_software_version }} fact definitions
  include_tasks: _install_facts.yml

- name: Set variables for {{ prometheus_software_name_version }} build
  set_fact:
    prometheus_software_binary: '{{ prometheus_software_root_dir }}/{{ prometheus_software_version }}__go-{{ prometheus_go_version }}/{{ prometheus_software_binary_name | default(prometheus_software_name, true) }}'
    prometheus_software_build_dir: '{{ prometheus_tmp_dir }}/{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_install_dir: '{{ prometheus_software_root_dir }}/{{ prometheus_software_version }}__go-{{ prometheus_go_version }}'

- name: Include task to setup directories for {{ prometheus_software_name_version }} installation
  include_tasks: _install_directory.yml

- name: Install {{ prometheus_software_name_version }} build prerequisites
  become: true
  package:
    name: '{{ prometheus_software_build_prerequisites }}'
    state: present
  when:
    - prometheus_software_build_prerequisites | length > 0

- name: Include task to setup environment for compiling go source code
  include_tasks: _install_go_compiler.yml
  when: prometheus_install_go_compiler_executed is not defined

- name: Gather statistics on the file {{ prometheus_software_binary }}
  stat:
    path: '{{ prometheus_software_binary }}'
  register: prometheus_software_binary_file

- name: Include task to build {{ prometheus_software_name_version }}
  include_tasks: _build_go_source.yml
  when: not prometheus_software_binary_file.stat.exists
