---
- name: Create {{ ansible_service_mgr }} configuration file for {{ prometheus_software_service_name }} service
  become: true
  template:
    dest: '/etc/systemd/system/{{ prometheus_software_service_name }}.service'
    src: ../templates/daemon-systemd.j2
    owner: root
    group: root
    mode: '0644'
  register: prometheus_software_init

- name: Enable {{ prometheus_software_service_name }} service
  become: true
  systemd:
    daemon_reload: '{{ prometheus_software_init.changed | lower | bool }}'
    state: started
    enabled: true
    name: '{{ prometheus_software_service_name }}'
  when: prometheus_software_service_test|bool

- name: Restart {{ prometheus_software_service_name }} service
  become: true
  service:
    daemon_reload: '{{ prometheus_software_init.changed | lower | bool }}'
    name: '{{ prometheus_software_service_name }}'
    state: restarted
  when: (prometheus_software_restart is defined and prometheus_software_restart | bool) or (prometheus_software_service_test | bool and (prometheus_software_installation is defined and prometheus_software_installation and prometheus_software_installation.changed) or prometheus_software_init.changed or (prometheus_software_cfg is defined and prometheus_software_cfg.changed))
