---
- name: Allow incoming prometheus server connections to {{ prometheus_software_name }}:{{ prometheus_software_instance_port | default(prometheus_software_port, true) }} via firewalld
  become: true
  firewalld:
    immediate: true
    port: '{{ prometheus_software_instance_port | default(prometheus_software_port, true) }}/tcp'
    permanent: true
    source: '{{ prometheus_server_ip }}'
    state: enabled
    zone: '{{ prometheus_firewalld_zone }}'
  loop_control:
    loop_var: prometheus_server_ip
  with_items: "{{ prometheus_server_ips }}"
  when:
    - prometheus_manage_client_firewalld|bool
    - prometheus_software_instance_port|default(prometheus_software_port, true)
    - prometheus_server_ips

- name: Allow incoming prometheus server connections to {{ prometheus_software_name }}:{{ prometheus_software_instance_port | default(prometheus_software_port, true) }} via iptables
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '{{ prometheus_software_instance_port | default(prometheus_software_port, true) }}'
    source: '{{ prometheus_server_ip }}'
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new {{ prometheus_software_name }} connections
  loop_control:
    loop_var: prometheus_server_ip
  with_items: "{{ prometheus_server_ips }}"
  when:
    - prometheus_manage_client_iptables|bool
    - prometheus_software_instance_port|default(prometheus_software_port, true)
    - prometheus_server_ips

- name: Include task for iptables_raw firewall management
  include_tasks: '_setup_firewall_iptables_raw.yml'
  when:
    - prometheus_manage_client_iptables_raw|bool
    - prometheus_software_instance_port|default(prometheus_software_port, true)
    - prometheus_server_ips
