---
- name: Include {{ prometheus_software_name }} variable file
  include_vars:
    name: prometheus_software_vars
    file: 'software/{{ prometheus_software_name }}.yml'

- name: Set {{ prometheus_software_name }} default software facts from software/{{ prometheus_software_name }}.yml
  set_fact:
    prometheus_software_default_git_master: '{{ prometheus_software_vars.software.master.commit.sha | default("") }}'
    prometheus_software_default_jobname: '{{ prometheus_software_vars.defaults.tgroup }}'
    prometheus_software_default_os_options: '{{ prometheus_software_vars.os_options | default({}) }}'
    prometheus_software_default_port: '{{ prometheus_software_vars.defaults.port }}'
    prometheus_software_default_prerelease: '{{ prometheus_software_vars.software.prerelease | default("") }}'
    prometheus_software_default_release: '{{ prometheus_software_vars.software.release | default("") }}'
    prometheus_software_default_src_url: '{{ prometheus_software_vars.software.source }}'
    prometheus_software_default_url: '{{ prometheus_software_vars.software.url }}'

- name: Set {{ prometheus_software_name }} os_options facts (part 1 of 2)
  set_fact:
    prometheus_software_os_options_list:
      - '{{ prometheus_software_default_os_options[ansible_distribution + "-" + ansible_distribution_major_version] | default("") }}'
      - '{{ prometheus_software_default_os_options[ansible_distribution + "-" + ansible_distribution_version] | default("") }}'
      - '{{ prometheus_software_default_os_options[ansible_distribution] | default("") }}'
      - '{{ prometheus_software_default_os_options[ansible_os_family + "-" + ansible_distribution_major_version] | default("") }}'
      - '{{ prometheus_software_default_os_options[ansible_os_family] | default("") }}'
      - '{{ prometheus_software_default_os_options["default"] | default("") }}'

- name: OS options facts
  debug:
    msg:
      - 'Default OS options: {{ prometheus_software_default_os_options }}'
      - 'OS options list: {{ prometheus_software_os_options_list }}'
  tags:
    # Only run if tagged debug
    - never
    - debug

- name: Set {{ prometheus_software_name }} os_option facts (part 2 of 2)
  set_fact:
    prometheus_software_os_options: '{{ prometheus_software_os_options_list | reject("equalto", "") | list | first | default("") }}'

- name: Default release version facts
  debug:
    msg:
      - 'Default release: {{ prometheus_software_default_release }}'
      - 'Default prerelease: {{ prometheus_software_default_prerelease }}'
  tags:
    # Only run if tagged debug
    - never
    - debug

- name: Set {{ prometheus_software_name }} version facts
  set_fact:
    prometheus_software_version: '{{ lookup("vars", "prometheus_" + prometheus_software_name + "_version", default=prometheus_software_default_release) }}'
    prometheus_software_use_prerelease: >-
      {{ lookup("vars", "prometheus_" + prometheus_software_name + "_use_prerelease", default=prometheus_software_use_prerelease) }}

- name: Software versions to use
  debug:
    msg:
      - 'Software version: {{ prometheus_software_version }}'
      - 'Use prerelease: {{ prometheus_software_use_prerelease }}'
  tags:
    # Only run if tagged debug
    - never
    - debug

- name: Set {{ prometheus_software_name }} prerelease version facts
  set_fact:
    prometheus_software_version: '{{ lookup("vars", "prometheus_" + prometheus_software_name + "_version", default=prometheus_software_default_prerelease) }}'
  when:
    - prometheus_software_use_prerelease
    - prometheus_software_default_prerelease | default(false)
    - prometheus_software_version | length < 1 or prometheus_software_default_prerelease is version(prometheus_software_version, 'gt')

- name: Set {{ prometheus_software_name }} version to git master as last resort
  set_fact:
    prometheus_software_version: '{{ prometheus_software_default_git_master }}'
  when:
    - prometheus_software_version is undefined or prometheus_software_version | length < 1

- name: Set {{ prometheus_software_name }} architecture facts
  set_fact:
    prometheus_software_architecture: '{{ prometheus_architecture }}'
  when: prometheus_software_architecture is undefined or prometheus_software_architecture | length < 1

- name: Software version and release facts
  debug:
    msg:
      - 'Architecture: {{ prometheus_software_architecture }}'
      - 'Software source master version): {{ prometheus_software_default_git_master }}'
      - 'Software version to use: {{ prometheus_software_version }}'
      - 'Software release list: {{ (prometheus_software_vars["software"]["releases"] | selectattr("name", "equalto", prometheus_software_version)) | list }}'
  tags:
    # Only run if tagged debug
    - never
    - debug

- name: Set {{ prometheus_software_name }} release facts
  set_fact:
    prometheus_software_release: >-
      {{ prometheus_software_vars["software"]["releases"] | selectattr("name", "equalto", prometheus_software_version) | list | first }}
  when:
    - prometheus_software_vars["software"]["releases"] | length > 0
    - prometheus_software_vars["software"]["releases"] | selectattr("name", "equalto", prometheus_software_version) | list | length > 0

- name: Software release being used
  debug:
    msg: 'Software release: {{ prometheus_software_release }}'
  when:
    - prometheus_software_release is defined
  tags:
    # Only run if tagged debug
    - never
    - debug

- name: Set {{ prometheus_software_name }} generic facts
  set_fact:
    prometheus_software_build_prerequisites: '{{ prometheus_software_os_options.build_prerequisites | default([]) }}'
    prometheus_software_env_vars: '{{ lookup("vars", "prometheus_" + prometheus_software_name + "_env_vars", default={}) }}'
    prometheus_software_extra_opts: '{{ lookup("vars", "prometheus_" + prometheus_software_name + "_extra_opts", default="") }}'
    prometheus_software_fallback_to_build: >-
      {{ lookup("vars", "prometheus_" + prometheus_software_name + "_fallback_to_build", default=prometheus_fallback_to_build) }}
    prometheus_software_host: '{{ lookup("vars", "prometheus_" + prometheus_software_name + "_host", default="0.0.0.0") }}'
    prometheus_software_metadata: >
      {{ prometheus_software_release.files | default([]) | selectattr("name", "match", "^.*" + prometheus_software_architecture + ".*$") |
      list | first | default({}) }}
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_port: '{{ lookup("vars", "prometheus_" + prometheus_software_name + "_port", default=prometheus_software_default_port) }}'
    prometheus_software_runas: '{{ lookup("vars", "prometheus_" + prometheus_software_name + "_runas", default=prometheus_user) }}'
    prometheus_software_src_dir_suffix:
      "{% if 'github.com' in prometheus_software_vars.software.source %}\
      /src/github.com/{{ prometheus_software_author }}/{{ prometheus_software_binary_name }}\
      {% else %}\
      {% endif %}"
    prometheus_software_src_url:
      "{% if 'https://github.com' in prometheus_software_default_src_url %}\
      {{ prometheus_software_default_url }}/archive/{{ prometheus_software_version }}.tar.gz\
      {% else %}\
      {{ prometheus_software_default_src_url }}\
      {% endif %}"
    prometheus_software_tgroup_jobname: >-
      {{ lookup("vars", "prometheus_" + prometheus_software_name + "_jobname", default=prometheus_software_default_jobname) }}
