---
- block:
  - name: 'Include role mesaguy.prometheus setup task'
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: 'Starting apache_exporter (lusitaniae) install'
  set_fact:
    prometheus_exporter: true
    prometheus_apache_exporter_lusitaniae_default_port: 9117
    prometheus_software_binary_name: 'apache_exporter'
    prometheus_software_env_vars: '{{ prometheus_apache_exporter_lusitaniae_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_apache_exporter_lusitaniae_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_apache_exporter_lusitaniae_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'apache_exporter_lusitaniae'
    prometheus_software_version: '{{ prometheus_apache_exporter_lusitaniae_version | default("0.5.0") }}'
    prometheus_software_src_version: '{{ prometheus_apache_exporter_lusitaniae_src_version | default("v0.5.0") }}'
    prometheus_software_description: 'Prometheus apache_exporter (lusitaniae), exporterapache mod_status statistics via HTTP'
    prometheus_software_documentation: 'https://github.com/Lusitaniae/apache_exporter'
    prometheus_software_host: '{{ prometheus_apache_exporter_lusitaniae_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_apache_exporter_lusitaniae_port | default(9117) }}'
    prometheus_software_runas: '{{ prometheus_apache_exporter_lusitaniae_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'apache_exporter'

- name: 'Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts'
  set_fact:
    prometheus_software_opts:
      - '-telemetry.address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/lusitaniae/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/lusitaniae/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/lusitaniae/{{ prometheus_software_shortname }}.git'

- name: 'Include task to perform installation of {{ prometheus_software_name_version }}'
  include_tasks: _install.yml

- name: 'Include task to setup {{ prometheus_software_name_version }} service'
  include_tasks: _service.yml

- name: 'Include task to perform post install cleanup of {{ prometheus_software_name_version }}'
  include_tasks: _post_install_cleanup.yml
