---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting cloudwatch_exporter install
  set_fact:
    prometheus_exporter: true
    prometheus_software_author: prometheus
    prometheus_software_binary_name: cloudwatch_exporter.jar
    prometheus_software_config: '{{ prometheus_cloudwatch_exporter_cfgs | default({"default" : ""}) }}'
    prometheus_software_name: cloudwatch_exporter
    prometheus_software_description: 'Prometheus cloudwatch_exporter, exporter for Amazon CloudWatch'
    prometheus_software_documentation: 'https://github.com/prometheus/cloudwatch_exporter'
    prometheus_software_service_test: '{{ prometheus_cloudwatch_exporter_service_test | default(true) }}'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} corrective facts
  set_fact:
    prometheus_software_version: '{{ prometheus_software_version | replace("cloudwatch_exporter-", "") }}'

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_prefix_command:
      - '{{ prometheus_java_path }}'
      - '-jar'
    prometheus_software_opts:
      - '{{ prometheus_software_port }} {{ prometheus_etc_dir }}/{{ prometheus_software_name }}.yml'
    prometheus_software_url:
      "https://search.maven.org/remotecontent?filepath=io/prometheus/cloudwatch/{{ prometheus_software_name }}/{{ prometheus_software_version }}/\
      {{ prometheus_software_name }}-{{ prometheus_software_version | regex_replace('^(v)?') }}-jar-with-dependencies.jar"

- name: Install standalone file for {{ prometheus_software_name_version }}
  include_tasks: _install_file.yml

- name: Setup {{ prometheus_software_name_version }} configuration files
  become: true
  template:
    src: 'templates/{{ prometheus_software_name }}.yml.j2'
    dest: '{{ prometheus_etc_dir }}/{{ prometheus_software_name }}.yml'
    owner: root
    group: '{{ prometheus_group }}'
    mode: 0640
    backup: true

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_version }}
  include_tasks: _post_install_cleanup.yml
