---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include couchdb_exporter (gesellix) variable file
  include_vars: exporters/couchdb_exporter_gesellix.yml

- name: Starting couchdb_exporter (gesellix) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'couchdb-prometheus-exporter'
    prometheus_software_env_vars: '{{ prometheus_couchdb_exporter_gesellix_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_couchdb_exporter_gesellix_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_couchdb_exporter_gesellix_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'couchdb_exporter_gesellix'
    prometheus_software_version: '{{ prometheus_couchdb_exporter_gesellix_version | default("18") }}'
    prometheus_software_src_version: '{{ prometheus_couchdb_exporter_gesellix_src_version | default("18") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_couchdb_exporter_gesellix_jobname | default("couchdb") }}'
    prometheus_software_description: 'Prometheus couchdb_exporter (gesellix), exporter of CouchDB statistics'
    prometheus_software_documentation: 'https://github.com/gesellix/couchdb-exporter'
    prometheus_software_host: '{{ prometheus_couchdb_exporter_gesellix_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_couchdb_exporter_gesellix_port | default(9984) }}'
    prometheus_software_runas: '{{ prometheus_couchdb_exporter_gesellix_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'couchdb-prometheus-exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '-telemetry.address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_src_dir_suffix: '/src/github.com/gesellix/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/gesellix/{{ prometheus_software_shortname }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
