---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include couchbase_exporter (blakelead) variable file
  include_vars: exporters/couchbase_exporter_blakelead.yml

- name: Starting couchbase_exporter (blakelead) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'couchbase_exporter'
    prometheus_software_binary_unarchive_opts: []
    prometheus_software_build_copy_dirs:
      - name: 'metrics'
        dir_mode: '0755'
        file_mode: '0644'
    prometheus_software_env_vars: '{{ prometheus_couchbase_exporter_blakelead_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_couchbase_exporter_blakelead_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_couchbase_exporter_blakelead_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'couchbase_exporter_blakelead'
    prometheus_software_version: '{{ prometheus_couchbase_exporter_blakelead_version | default("0.9.2") }}'
    prometheus_software_src_version: '{{ prometheus_couchbase_exporter_blakelead_src_version | default("0.9.2") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_couchbase_exporter_blakelead_jobname | default(prometheus_couchbase_exporter_blakelead_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus couchbase_exporter (blakelead), exporter of Couchbase statistics'
    prometheus_software_documentation: 'https://github.com/blakelead/couchbase_exporter'
    prometheus_software_host: '{{ prometheus_couchbase_exporter_blakelead_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_couchbase_exporter_blakelead_port | default(prometheus_couchbase_exporter_blakelead_default_port) }}'
    prometheus_software_runas: '{{ prometheus_couchbase_exporter_blakelead_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'couchbase_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    # No binaries released for 0.9.2
    # prometheus_software_bin_url: 'https://github.com/blakelead/{{ prometheus_software_shortname }}/releases/download/{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}-{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/blakelead/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/leansys-team/{{ prometheus_software_shortname }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
