---
- block:
  - name: 'Include role mesaguy.prometheus setup task'
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: 'Starting digitalocean_exporter install'
  set_fact:
    prometheus_exporter: true
    prometheus_digitalocean_exporter_default_port: 9212
    prometheus_software_binary_name: 'digitalocean_exporter'
    prometheus_software_binary_unarchive_opts: []
    prometheus_software_env_vars: '{{ prometheus_digitalocean_exporter_metalmatze_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_digitalocean_exporter_metalmatze_extra_opts | default () }}'
    # Do not perform tests, tests only succeed where IPv6 is available
    prometheus_software_fallback_to_build: '{{ prometheus_digitalocean_exporter_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'digitalocean_exporter_metalmatze'
    prometheus_software_version: '{{ prometheus_digitalocean_exporter_version | default("0.5") }}'
    prometheus_software_src_version: '{{ prometheus_digitalocean_exporter_src_version | default("v0.5") }}'
    prometheus_software_description: 'Prometheus digitalocean_exporter, export from arbitrary unstructured log data'
    prometheus_software_documentation: 'https://github.com/metalmatze/digitalocean_exporter'
    prometheus_software_host: '{{ prometheus_digitalocean_exporter_metalmatze_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_digitalocean_exporter_metalmatze_port | default(9212) }}'
    prometheus_software_runas: '{{ prometheus_digitalocean_exporter_metalmatze_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'digitalocean_exporter'

- name: 'Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts'
  set_fact:
    prometheus_software_config_name: '{{ prometheus_software_name }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_opts:
      - '--webaddr={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_file_url: 'https://github.com/metalmatze/{{ prometheus_software_shortname }}/releases/download/{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}-{{ prometheus_architecture }}'
    prometheus_software_src_dir_suffix: '/src/github.com/metalmatze/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/metalmatze/{{ prometheus_software_shortname }}'

- name: 'Include task to perform installation of {{ prometheus_software_name_version }}'
  include_tasks: _install_file.yml

- name: 'Include task to setup {{ prometheus_software_name_version }} service'
  include_tasks: _service.yml

- name: 'Include task to perform post install cleanup of {{ prometheus_software_name_version }}'
  include_tasks: _post_install_cleanup.yml
