---
- block:
  - name: 'Include role mesaguy.prometheus setup task'
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include elasticsearch_exporter (justwatchcom) variable file
  include_vars: exporters/elasticsearch_exporter_justwatchcom.yml

- name: Starting elasticsearch_exporter (justwatchcom) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'elasticsearch_exporter'
    prometheus_software_env_vars: '{{ prometheus_elasticsearch_exporter_justwatchcom_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_elasticsearch_exporter_justwatchcom_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_elasticsearch_exporter_justwatchcom_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'elasticsearch_exporter_justwatchcom'
    prometheus_software_version: '{{ prometheus_elasticsearch_exporter_justwatchcom_version | default("1.0.2") }}'
    prometheus_software_src_version: '{{ prometheus_elasticsearch_exporter_justwatchcom_src_version | default("v1.0.2") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_elasticsearch_exporter_justwatchcom_jobname | default(prometheus_elasticsearch_exporter_justwatchcom_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus elasticsearch_exporter (justwatchcom), exporter for various metrics about ElasticSearch'
    prometheus_software_documentation: 'https://github.com/justwatchcom/elasticsearch_exporter'
    prometheus_software_host: '{{ prometheus_elasticsearch_exporter_justwatchcom_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_elasticsearch_exporter_justwatchcom_port | default(prometheus_elasticsearch_exporter_justwatchcom_default_port) }}'
    prometheus_software_runas: '{{ prometheus_elasticsearch_exporter_justwatchcom_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'elasticsearch_exporter'

- name: 'Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts'
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/justwatchcom/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/justwatchcom/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/justwatchcom/{{ prometheus_software_shortname }}.git'

- name: 'Include task to perform installation of {{ prometheus_software_name_version }}'
  include_tasks: _install.yml

- name: 'Include task to setup {{ prometheus_software_name_version }} service'
  include_tasks: _service.yml

- name: 'Include task to perform post install cleanup of {{ prometheus_software_name_version }}'
  include_tasks: _post_install_cleanup.yml
