---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include grok_exporter (fstab) variable file
  include_vars: exporters/grok_exporter_fstab.yml

- name: Starting grok_exporter (fstab) install
  set_fact:
    prometheus_exporter: true
    prometheus_grok_exporter_fstab_patterns_directory: '{{ prometheus_grok_exporter_fstab_patterns_dir | default(prometheus_etc_dir + "/grok_patterns") }}'
    prometheus_grok_exporter_fstab_sync_patterns_directory: true
    prometheus_software_binary_name: 'grok_exporter'
    prometheus_software_binary_unarchive_opts: []
    prometheus_software_env_vars: '{{ prometheus_gork_exporter_fstab_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_grok_exporter_fstab_extra_opts | default () }}'
    # Do not perform tests, tests only succeed where IPv6 is available
    prometheus_software_fallback_to_build: '{{ prometheus_grok_exporter_fstab_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'grok_exporter_fstab'
    prometheus_software_version: '{{ prometheus_grok_exporter_fstab_version | default("0.2.8") }}'
    # prometheus_software_src_version: '{{ prometheus_grok_exporter_fstab_src_version | default("v0.2.8") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_grok_exporter_fstab_jobname | default(prometheus_grok_exporter_fstab_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus grok_exporter, export from arbitrary unstructured log data'
    prometheus_software_documentation: 'https://github.com/fstab/grok_exporter'
    prometheus_software_host: '{{ prometheus_grok_exporter_fstab_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_grok_exporter_fstab_port | default(prometheus_grok_exporter_fstab_default_port) }}'
    prometheus_software_runas: '{{ prometheus_grok_exporter_fstab_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'grok_exporter'

- name: 'Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts'
  set_fact:
    prometheus_software_config_name: '{{ prometheus_software_name }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_opts:
      - '-config {{ prometheus_etc_dir }}/grok_exporter_fstab.yml'
    prometheus_software_bin_url: 'https://github.com/fstab/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.zip'
    # Source builds are unrealistic unless we build Oniguruma libraries too...:
    #   https://github.com/fstab/grok_exporter/
    # prometheus_software_src_dir_suffix: '/src/github.com/fstab/{{ prometheus_software_shortname }}'
    # prometheus_software_src_url: 'https://github.com/fstab/{{ prometheus_software_shortname }}'

- name: 'Include task to perform installation of {{ prometheus_software_name_version }}'
  include_tasks: _install.yml

- name: 'Setup {{ prometheus_software_name_version }} configuration file'
  become: true
  copy:
    content: '{{ prometheus_grok_exporter_fstab_cfg | default(lookup("file", "../files/grok_exporter_fstab.yml")) }}'
    dest: '{{ prometheus_etc_dir }}/grok_exporter_fstab.yml'
    owner: root
    group: root
    mode: '0644'
    backup: true
  register: prometheus_software_cfg

- name: Find the {{ prometheus_software_shortname }} binary
  find:
    paths: '{{ prometheus_software_install_dir }}'
    patterns: '{{ prometheus_software_binary_name }}'
    file_type: file
    recurse: true
  register: prometheus_binary_file_location

- name: Include task to move {{ prometheus_software_name_version }} files down one directory
  include_tasks: _move_files_down_one_directory.yml
  when: prometheus_binary_file_location.files and prometheus_binary_file_location.files[0].path != prometheus_software_install_dir + '/' + prometheus_software_binary_name

- name: Synchronize the {{ prometheus_software_name_version }} example grok patterns to {{ prometheus_grok_exporter_fstab_patterns_directory }}
  include_tasks: _copy_remote_directory_contents.yml
  vars:
    prometheus_copy_dest_dir: '{{ prometheus_grok_exporter_fstab_patterns_directory }}'
    prometheus_copy_src_dir: '{{ prometheus_software_install_dir }}/patterns'
    prometheus_copy_dir_mode: '0755'
    prometheus_copy_file_mode: '0644'
  when: prometheus_grok_exporter_fstab_sync_patterns_directory | bool

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
