---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting haproxy_exporter install
  set_fact:
    prometheus_exporter: true
    prometheus_software_author: prometheus
    prometheus_software_binary_name: haproxy_exporter
    prometheus_software_name: haproxy_exporter
    prometheus_software_description: 'Prometheus haproxy_exporter, exporter of host statistics'
    prometheus_software_documentation: 'https://github.com/prometheus/haproxy_exporter'
    prometheus_software_makefile_make_command: make build

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts: >
      [{% if prometheus_haproxy_exporter_socket is defined and prometheus_haproxy_exporter_socket %}
      "--haproxy.scrape-uri=unix:{{ prometheus_haproxy_exporter_socket }}"
      {% else %}
      "--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}"
      {% endif %}]
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/{{ prometheus_software_name }}/releases/download/{{ prometheus_software_version }}/\
      {{ prometheus_software_name }}-{{ prometheus_software_version | regex_replace('^(v)?') }}.{{ prometheus_software_architecture }}.tar.gz"

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
