---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting ipmi_exporter (soundcloud) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_author: soundcloud
    prometheus_software_binary_name: ipmi_exporter
    prometheus_software_makefile_make_command: 'make build'
    prometheus_software_name: ipmi_exporter_soundcloud
    prometheus_software_description: 'Prometheus ipmi_exporter for exporting IPMI statistics'
    prometheus_software_documentation: 'https://github.com/soundcloud/ipmi_exporter'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_config_name: '{{ prometheus_software_name }}'
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Setup {{ prometheus_software_name_version }} configuration file
  become: true
  copy:
    content: '{{ prometheus_ipmi_exporter_soundcloud_cfg | default(lookup("file", "../files/ipmi_exporter_soundcloud.yml")) }}'
    dest: '{{ prometheus_etc_dir }}/ipmi_exporter_soundcloud.yml'
    owner: root
    group: '{{ prometheus_group }}'
    mode: 0640
    backup: true
  notify:
    - Restart Prometheus service

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
