---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include iptables_exporter (retailnext) variable file
  include_vars: exporters/iptables_exporter_retailnext.yml

- name: Starting iptables_exporter (retailnext) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'iptables_exporter'
    prometheus_software_env_vars: '{{ prometheus_iptables_exporter_retailnext_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_iptables_exporter_retailnext_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_iptables_exporter_retailnext_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'iptables_exporter_retailnext'
    prometheus_software_version: '{{ prometheus_iptables_exporter_retailnext_version | default("0.1.0") }}'
    prometheus_software_src_version: '{{ prometheus_iptables_exporter_retailnext_src_version | default("v0.1.0") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_iptables_exporter_retailnext_jobname | default(prometheus_iptables_exporter_retailnext_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus iptables_exporter (retailnext), exporter for IPTables metrics'
    prometheus_software_documentation: 'https://github.com/retailnext/iptables_exporter'
    prometheus_software_host: '{{ prometheus_iptables_exporter_retailnext_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_iptables_exporter_retailnext_port | default(prometheus_iptables_exporter_retailnext_default_port) }}'
    prometheus_software_runas: '{{ prometheus_iptables_exporter_retailnext_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'iptables_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/retailnext/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/retailnext/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/retailnext/{{ prometheus_software_shortname }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
