---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting iptables_exporter (retailnext) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_systemd_options:
      - 'CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_NET_RAW'
      - 'AmbientCapabilities=CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_NET_RAW'
    prometheus_software_author: retailnext
    prometheus_software_binary_name: iptables_exporter
    prometheus_software_makefile_make_command: 'go get -d && go build'
    prometheus_software_name: iptables_exporter_retailnext
    prometheus_software_description: 'Prometheus iptables_exporter (retailnext), exporter for IPTables metrics'
    prometheus_software_documentation: 'https://github.com/retailnext/iptables_exporter'
    # No official releases are available
    prometheus_software_use_prerelease: true

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/{{ prometheus_software_binary_name }}/releases/download/{{ prometheus_software_version }}/\
      {{ prometheus_software_binary_name }}-{{ prometheus_software_version | regex_replace('^(v)?') }}.{{ prometheus_software_architecture }}.tar.gz"

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
