---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting jmx_exporter install
  set_fact:
    prometheus_exporter: true
    prometheus_software_author: prometheus
    prometheus_software_binary_name: jmx_exporter.jar
    prometheus_software_config: '{{ prometheus_jmx_exporter_cfgs | default({"default" : ""}) }}'
    prometheus_software_name: jmx_exporter
    prometheus_software_description: 'Prometheus jmx_exporter, JMX to Prometheus exporter'
    prometheus_software_documentation: 'https://github.com/prometheus/jmx_exporter'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} corrective facts
  set_fact:
    prometheus_software_version: '{{ prometheus_software_version | replace("parent-", "") }}'

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_url:
      "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/{{ prometheus_software_version }}/\
      jmx_prometheus_javaagent-{{ prometheus_software_version | regex_replace('^(v)?') }}.jar"
    prometheus_software_src_dir_suffix: '/src/github.com/{{ prometheus_software_author }}/{{ prometheus_software_name }}'

- name: Install standalone file for {{ prometheus_software_name_version }}
  include_tasks: _install_file.yml

- name: Setup {{ prometheus_software_name_version }} configuration files
  become: true
  template:
    src: 'templates/jmx-config.yml.j2'
    dest: '{{ prometheus_etc_dir }}/{{ prometheus_software_name }}.{{ jmx_instance.key }}.yml'
    owner: root
    group: '{{ prometheus_group }}'
    mode: '{{ prometheus_jmx_exporter_cfg_mode | default(0640) }}'
    backup: true
  loop_control:
    loop_var: jmx_instance
  with_dict: '{{ prometheus_software_config }}'

- name: Include task to perform post install cleanup of {{ prometheus_software_version }}
  include_tasks: _post_install_cleanup.yml
