---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include kafka_exporter (danielqsj) variable file
  include_vars: exporters/kafka_exporter_danielqsj.yml

- name: Starting kafka_exporter (danielqsj) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: kafka_exporter
    prometheus_software_env_vars: '{{ prometheus_kafka_exporter_danielqsj_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_kafka_exporter_danielqsj_extra_opts | default () }}'
    prometheus_software_fallback_to_build: '{{ prometheus_kafka_exporter_danielqsj_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: kafka_exporter_danielqsj
    prometheus_software_version: '{{ prometheus_kafka_exporter_danielqsj_version | default("1.2.0") }}'
    prometheus_software_src_version: '{{ prometheus_kafka_exporter_danielqsj_src_version | default("v1.2.0") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_kafka_exporter_danielqsj_jobname | default(prometheus_kafka_exporter_danielqsj_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus kafka_exporter (danielqsj), exporter of Apache Kafka metrics'
    prometheus_software_documentation: 'https://github.com/danielqsj/kafka_exporter'
    prometheus_software_host: '{{ prometheus_kafka_exporter_danielqsj_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_kafka_exporter_danielqsj_port | default(prometheus_kafka_exporter_danielqsj_default_port) }}'
    prometheus_software_service_test: '{{ prometheus_kafka_exporter_danielqsj_service_test | default(true) }}'
    prometheus_software_runas: '{{ prometheus_kafka_exporter_danielqsj_runas | default(prometheus_user) }}'
    prometheus_software_shortname: kafka_exporter

- name: Set {{ prometheus_software_shortname }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/danielqsj/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/danielqsj/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/danielqsj/{{ prometheus_software_shortname }}'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
