---
- block:
  - name: 'Include role mesaguy.prometheus setup task'
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: 'Starting memcached_exporter install'
  set_fact:
    prometheus_exporter: true
    prometheus_memcached_exporter_default_port: 9150
    prometheus_software_makefile_make_command: 'make format && make build'
    prometheus_software_extra_opts: '{{ prometheus_memcached_exporter_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_memcached_exporter_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'memcached_exporter'
    prometheus_software_version: '{{ prometheus_memcached_exporter_version | default("0.4.1") }}'
    prometheus_software_src_version: '{{ prometheus_memcached_exporter_src_version | default("v0.4.1") }}'
    prometheus_software_description: 'Prometheus memcached_exporter, exporter of host statistics'
    prometheus_software_documentation: 'https://github.com/prometheus/memcached_exporter/blob/master/README.md'
    prometheus_software_host: '{{ prometheus_memcached_exporter_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_memcached_exporter_port | default(9150) }}'
    prometheus_software_runas: '{{ prometheus_memcached_exporter_runas | default(prometheus_user) }}'

- name: 'Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts'
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/prometheus/{{ prometheus_software_name }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_name }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/prometheus/{{ prometheus_software_name }}'
    prometheus_software_src_url: 'https://github.com/prometheus/{{ prometheus_software_name }}.git'

- name: 'Include task to perform installation of {{ prometheus_software_name_version }}'
  include_tasks: _install.yml

- name: 'Include task to setup {{ prometheus_software_name_version }} service'
  include_tasks: _service.yml

- name: 'Include task to perform post install cleanup of {{ prometheus_software_name_version }}'
  include_tasks: _post_install_cleanup.yml
