---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting mongodb_exporter (percona) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_author: percona
    prometheus_software_binary_name: mongodb_exporter
    prometheus_software_makefile_make_command: 'go get -d && go build'
    prometheus_software_name: mongodb_exporter_percona
    prometheus_software_description: 'Prometheus mongodb_exporter (percona), exporter of MongoDB statistics'
    prometheus_software_documentation: 'https://github.com/percona/mongodb_exporter'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/{{ prometheus_software_binary_name }}/releases/download/{{ prometheus_software_version }}/\
      {{ prometheus_software_binary_name }}-{{ prometheus_software_version | regex_replace('^(v)?') }}.{{ prometheus_software_architecture }}.tar.gz"

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
