---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include mysqld_exporter variable file
  include_vars: exporters/mysqld_exporter.yml

- name: Starting mysqld_exporter install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'mysqld_exporter'
    prometheus_software_env_vars: '{{ prometheus_mysqld_exporter_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_mysqld_exporter_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_mysqld_exporter_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_makefile_make_command: 'make build'
    prometheus_software_name: 'mysqld_exporter'
    prometheus_software_version: '{{ prometheus_mysqld_exporter_version | default("0.12.1") }}'
    prometheus_software_src_version: '{{ prometheus_mysqld_exporter_src_version | default("v0.12.1") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_mysqld_exporter_jobname | default(prometheus_mysqld_exporter_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus mysqld_exporter, exporter of host statistics'
    prometheus_software_documentation: 'https://github.com/prometheus/mysqld_exporter'
    prometheus_software_host: '{{ prometheus_mysqld_exporter_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_mysqld_exporter_port | default(prometheus_mysqld_exporter_default_port) }}'
    prometheus_software_runas: '{{ prometheus_mysqld_exporter_runas | default(prometheus_user) }}'
    prometheus_software_service_test: '{{ prometheus_mysqld_exporter_service_test | default(true) }}'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/prometheus/{{ prometheus_software_name }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_name }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/prometheus/{{ prometheus_software_name }}'
    prometheus_software_src_url: 'https://github.com/prometheus/{{ prometheus_software_name }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- block:
    - name: Collect "{{ prometheus_user}}" user information
      user:
        name: '{{ prometheus_user }}'
      register: prometheus_user_registered

    - name: Copy {{ prometheus_software_name_version }} credentials to {{ prometheus_user_registered.home }}/.my.cnf
      become: true
      template:
        src: ../templates/mysqld_exporter-my.cnf.j2
        dest: '{{ prometheus_user_registered.home }}/.my.cnf'
        owner: '{{ prometheus_user }}'
        group: '{{ prometheus_group }}'
        mode: '0400'
      notify:
        - Restart Prometheus service
      register: prometheus_mysqld_exporter_credentials
  when:
    - prometheus_mysqld_exporter_username is defined and prometheus_mysqld_exporter_username
    - prometheus_mysqld_exporter_password is defined and prometheus_mysqld_exporter_password

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
