---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include ntp_exporter (sapcc) variable file
  include_vars: exporters/ntp_exporter_sapcc.yml

- name: Starting ntp_exporter (sapcc) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_files:
      - 'build/ntp_exporter'
    prometheus_software_binary_name: 'ntp_exporter'
    prometheus_software_env_vars: '{{ prometheus_ntp_exporter_sapcc_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_ntp_exporter_sapcc_extra_opts | default () }}'
    # Do not perform tests, tests only succeed where IPv6 is available
    prometheus_software_fallback_to_build: '{{ prometheus_ntp_exporter_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'ntp_exporter_sapcc'
    prometheus_software_version: '{{ prometheus_ntp_exporter_src_version | default("v1.1.1") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_ntp_exporter_sapcc_jobname | default("ntp") }}'
    prometheus_software_description: "Prometheus ntp_exporter, checks the drift of that node's clock against a given NTP server"
    prometheus_software_documentation: 'https://github.com/sapcc/ntp_exporter'
    prometheus_software_host: '{{ prometheus_ntp_exporter_sapcc_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_ntp_exporter_sapcc_port | default(9559) }}'
    prometheus_software_shortname: 'ntp_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_opts:
      - '-web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_src_dir_suffix: '/src/github.com/sapcc/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/sapcc/{{ prometheus_software_shortname }}'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
