---
- block:
  - name: 'Include role mesaguy.prometheus setup task'
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: 'Starting nvidia_gpu_exporter (mindprince) install'
  set_fact:
    prometheus_exporter: true
    prometheus_nvidia_gpu_exporter_mindprince_default_port: 9445
    prometheus_software_binary_name: 'nvidia_gpu_prometheus_exporter'
    prometheus_software_env_vars: '{{ prometheus_nvidia_gpu_exporter_mindprince_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_nvidia_gpu_exporter_mindprince_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_nvidia_gpu_exporter_mindprince_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_officialname: 'nvidia_gpu_prometheus_exporter'
    prometheus_software_makefile_make_command: 'go get -d && go build'
    prometheus_software_name: 'nvidia_gpu_exporter_mindprince'
    prometheus_software_version: '{{ prometheus_nvidia_gpu_exporter_mindprince_version | default("3897bdad246f3bc0e7105805d4442b9c9c7b06d2") }}'
    prometheus_software_description: 'Prometheus nvidia_gpu_exporter (mindprince), exporter of NVIDIA GPU metrics'
    prometheus_software_documentation: 'https://github.com/mindprince/nvidia_gpu_prometheus_exporter'
    prometheus_software_host: '{{ prometheus_nvidia_gpu_exporter_mindprince_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_nvidia_gpu_exporter_mindprince_port | default(9445) }}'
    prometheus_software_runas: '{{ prometheus_nvidia_gpu_exporter_mindprince_runas | default(prometheus_user) }}'
    prometheus_software_service_test: '{{ prometheus_nvidia_gpu_exporter_mindprince_service_test | default(true) }}'
    prometheus_software_shortname: 'nvidia_gpu_exporter'

- name: 'Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts'
  set_fact:
    prometheus_software_opts:
      - '-web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_src_dir_suffix: '/src/github.com/mindprince/nvidia_gpu_prometheus_exporter'
    prometheus_software_src_url: 'https://github.com/mindprince/nvidia_gpu_prometheus_exporter/archive/{{ prometheus_software_version }}.tar.gz'

- name: 'Include task to perform installation of {{ prometheus_software_name_version }}'
  include_tasks: _install.yml

- name: 'Include task to setup {{ prometheus_software_name_version }} service'
  include_tasks: _service.yml

- name: 'Include task to perform post install cleanup of {{ prometheus_software_name_version }}'
  include_tasks: _post_install_cleanup.yml
