---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include openldap_exporter (tomcz) variable file
  include_vars: exporters/openldap_exporter_tomcz.yml

- name: Starting openldap_exporter (tomcz) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'openldap_exporter'
    prometheus_software_env_vars: '{{ prometheus_openldap_exporter_tomcz_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_openldap_exporter_tomcz_extra_opts | default () }}'
    # Do not perform tests, tests only succeed where IPv6 is available
    prometheus_software_fallback_to_build: '{{ prometheus_openldap_exporter_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'openldap_exporter_tomcz'
    prometheus_software_version: '{{ prometheus_openldap_exporter_version | default("1.0") }}'
    prometheus_software_src_version: '{{ prometheus_openldap_exporter_src_version | default("v1.0") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_openldap_exporter_tomcz_jobname | default("openldap") }}'
    prometheus_software_description: 'Prometheus openldap_exporter, OpenLDAP Exporter'
    prometheus_software_documentation: 'https://github.com/tomcz/openldap_exporter'
    prometheus_software_host: '{{ prometheus_openldap_exporter_tomcz_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_openldap_exporter_tomcz_port | default(9330) }}'
    prometheus_software_runas: '{{ prometheus_openldap_exporter_tomcz_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'openldap_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_config_name: '{{ prometheus_software_name }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_opts:
      - '-promAddr={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_file_url: 'https://github.com/tomcz/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_architecture | replace("linux-amd64", "linux") }}'
    prometheus_software_src_dir_suffix: '/src/github.com/tomcz/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/tomcz/{{ prometheus_software_shortname }}'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install_file.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
