---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include openvpn_exporter (kumina) variable file
  include_vars: exporters/openvpn_exporter_kumina.yml

- name: Starting openvpn_exporter (kumina) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'openvpn_exporter'
    prometheus_software_env_vars: '{{ prometheus_openvpn_exporter_kumina_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_openvpn_exporter_kumina_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_openvpn_exporter_kumina_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_officialname: 'openvpn_exporter_kumina'
    prometheus_software_name: 'openvpn_exporter_kumina'
    prometheus_software_version: '{{ prometheus_openvpn_exporter_kumina_version | default("0.2.1") }}'
    prometheus_software_src_version: '{{ prometheus_node_exporter_src_version | default("v0.2.1") }}'
    prometheus_software_description: 'Prometheus openvpn_exporter (kumina), exporter of OpenVPN metrics'
    prometheus_software_documentation: 'https://github.com/kumina/openvpn_exporter'
    prometheus_software_host: '{{ prometheus_openvpn_exporter_kumina_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_openvpn_exporter_kumina_port | default(9176) }}'
    prometheus_software_runas: '{{ prometheus_openvpn_exporter_kumina_runas | default(prometheus_user) }}'
    prometheus_software_service_test: '{{ prometheus_openvpn_exporter_kumina_service_test | default(true) }}'
    prometheus_software_shortname: 'openvpn_exporter'
    prometheus_software_tgroup_jobname: '{{ prometheus_openvpn_exporter_kumina_jobname | default("openvpn") }}'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '-web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_src_dir_suffix: '/src/github.com/kumina/openvpn_exporter'
    prometheus_software_src_url: 'https://github.com/kumina/openvpn_exporter/archive/{{ prometheus_software_src_version }}.tar.gz'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
