---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting ping_exporter (czerwonk) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_author: czerwonk
    prometheus_software_binary_name: ping_exporter
    prometheus_software_capabilities:
      ping_exporter:
        - cap_net_raw+ep
    prometheus_software_name: ping_exporter_czerwonk
    prometheus_software_description: 'Prometheus ping_exporter for ICMP echo requests'
    prometheus_software_documentation: 'https://github.com/czerwonk/ping_exporter'

- name: Set {{ prometheus_software_name }} architecture facts
  set_fact:
    prometheus_software_architecture: '{{ prometheus_architecture | replace("-", "_") }}'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_config_name: '{{ prometheus_software_name }}'
    prometheus_software_opts:
      - '--config.path={{ prometheus_etc_dir }}/{{ prometheus_software_name }}.yml'
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/{{ prometheus_software_binary_name }}/releases/download/{{ prometheus_software_version }}/\
      {{ prometheus_software_binary_name }}-{{ prometheus_software_version | regex_replace('^(v)?') }}_\
      {{ prometheus_software_architecture | replace('-', '_') }}"

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install_file.yml

- name: Setup {{ prometheus_software_name_version }} configuration file
  become: true
  template:
    src: 'templates/{{ prometheus_software_name }}.yml.j2'
    dest: '{{ prometheus_etc_dir }}/{{ prometheus_software_name }}.yml'
    owner: root
    group: '{{ prometheus_group }}'
    mode: 0640
    backup: true
  notify:
    - Restart Prometheus service

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
