---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include ping_exporter (czerwonk) variable file
  include_vars: exporters/ping_exporter_czerwonk.yml

- name: Starting ping_exporter (czerwonk) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'ping_exporter'
    prometheus_software_capabilities:
      ping_exporter:
        - cap_net_raw+p
    prometheus_software_env_vars: '{{ prometheus_ping_exporter_czerwonk_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_ping_exporter_czerwonk_extra_opts | default () }}'
    # Do not perform tests, tests only succeed where IPv6 is available
    prometheus_software_fallback_to_build: '{{ prometheus_ping_exporter_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'ping_exporter_czerwonk'
    prometheus_software_version: '{{ prometheus_ping_exporter_version | default("0.4.4") }}'
    prometheus_software_src_version: '{{ prometheus_ping_exporter_src_version | default("0.44") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_ping_exporter_czerwonk_jobname | default("ping") }}'
    prometheus_software_description: 'Prometheus ping_exporter for ICMP echo requests'
    prometheus_software_documentation: 'https://github.com/czerwonk/ping_exporter'
    prometheus_software_host: '{{ prometheus_ping_exporter_czerwonk_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_ping_exporter_czerwonk_port | default(9427) }}'
    prometheus_software_runas: '{{ prometheus_ping_exporter_czerwonk_runas | default("root") }}'
    prometheus_software_shortname: 'ping_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_config_name: '{{ prometheus_software_name }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_opts:
      - '-config.path={{ prometheus_etc_dir }}/{{ prometheus_software_name }}.yml'
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_file_url: 'https://github.com/czerwonk/{{ prometheus_software_shortname }}/releases/download/{{ prometheus_software_src_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}_{{ prometheus_architecture | replace("-", "_") }}'
    prometheus_software_src_dir_suffix: '/src/github.com/czerwonk/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/czerwonk/{{ prometheus_software_shortname }}'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install_file.yml

- name: Setup {{ prometheus_software_name_version }} configuration file
  become: true
  template:
    src: '../templates/{{ prometheus_software_name }}.yml.j2'
    dest: '{{ prometheus_etc_dir }}/{{ prometheus_software_name }}.yml'
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - Restart Prometheus service

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
