---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting postgres_exporter (prometheus-community) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_author: prometheus-community
    prometheus_software_binary_name: postgres_exporter
    prometheus_software_make_command: 'go run mage.go binary'
    prometheus_software_makefile_make_command: 'go run mage.go binary'
    prometheus_software_name: postgres_exporter_prometheus_community
    prometheus_software_description: 'Prometheus postgres_exporter (prometheus-community), exporter of host statistics'
    prometheus_software_documentation: 'https://github.com/prometheus-community/postgres_exporter'


- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/{{ prometheus_software_binary_name }}/releases/download/{{ prometheus_software_version }}\
      /{{ prometheus_software_binary_name }}_{{ prometheus_software_version }}_{{ prometheus_software_architecture }}.tar.gz"

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
