---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include postgres_exporter (wrouesnel) variable file
  include_vars: exporters/postgres_exporter_wrouesnel.yml

- name: Starting postgres_exporter (wrouesnel) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'postgres_exporter'
    prometheus_software_env_vars: '{{ prometheus_postgres_exporter_wrouesnel_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_postgres_exporter_wrouesnel_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_postgres_exporter_wrouesnel_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_make_command: 'go run mage.go binary'
    prometheus_software_makefile_make_command: 'go run mage.go binary'
    prometheus_software_name: 'postgres_exporter_wrouesnel'
    prometheus_software_version: '{{ prometheus_postgres_exporter_wrouesnel_version | default("0.5.0") }}'
    prometheus_software_src_version: '{{ prometheus_postgres_exporter_wrouesnel_src_version | default("v0.5.0") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_postgres_exporter_wrouesnel_jobname | default(prometheus_postgres_exporter_wrouesnel_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus postgres_exporter (wrouesnel), exporter of host statistics'
    prometheus_software_documentation: 'https://github.com/wrouesnel/postgres_exporter'
    prometheus_software_host: '{{ prometheus_postgres_exporter_wrouesnel_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_postgres_exporter_wrouesnel_port | default(prometheus_postgres_exporter_wrouesnel_default_port) }}'
    prometheus_software_runas: '{{ prometheus_postgres_exporter_wrouesnel_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'postgres_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/wrouesnel/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}_v{{ prometheus_software_version }}_{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/wrouesnel/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/wrouesnel/{{ prometheus_software_shortname }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
