---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Starting pushgateway install
  set_fact:
    prometheus_exporter: false
    prometheus_software_binary_name: 'pushgateway'
    prometheus_software_env_vars: '{{ prometheus_pushgateway_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_pushgateway_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_pushgateway_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_makefile_make_command: 'make build'
    prometheus_software_name: 'pushgateway'
    prometheus_software_version: '{{ prometheus_pushgateway_version | default("1.1.0") }}'
    prometheus_software_src_version: '{{ prometheus_pushgateway_src_version | default("v1.1.0") }}'
    prometheus_software_description: 'Prometheus pushgateway'
    prometheus_software_documentation: 'https://github.com/prometheus/pushgateway'
    prometheus_software_host: '{{ prometheus_pushgateway_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_pushgateway_port | default(9091) }}'
    prometheus_software_runas: '{{ prometheus_pushgateway_runas | default(prometheus_user) }}'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_config_name: '{{ prometheus_software_name }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_bin_url: 'https://github.com/prometheus/{{ prometheus_software_name }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_name }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/prometheus/{{ prometheus_software_name }}'
    prometheus_software_src_url: 'https://github.com/prometheus/{{ prometheus_software_name }}'

- name: 'Create {{ prometheus_software_name_version }} persistence storage file directory'
  become: true
  file:
    path: '{{ prometheus_pushgateway_persistence_dir }}'
    state: directory
    owner: '{{ prometheus_user }}'
    group: '{{ prometheus_group }}'
    mode: '0750'
  when: prometheus_pushgateway_persistence_dir is defined

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
