---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting rabbitmq_exporter (kbudde) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_allow_build_test: true
    prometheus_software_author: kbudde
    prometheus_software_binary_name: rabbitmq_exporter
    prometheus_software_makefile_make_command: 'go get -d && make build'
    prometheus_software_name: rabbitmq_exporter_kbudde
    prometheus_software_description: 'Prometheus rabbitmq_exporter (kbudde), exporter for RabbitMQ metrics'
    prometheus_software_documentation: 'https://github.com/kbudde/rabbitmq_exporter'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_env_vars: >
        {{ { "PUBLISH_ADDR": prometheus_software_host, "PUBLISH_PORT": prometheus_software_port } | combine(prometheus_software_env_vars) }}
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/{{ prometheus_software_binary_name }}/releases/download/{{ prometheus_software_version }}/\
      {{ prometheus_software_binary_name }}-{{ prometheus_software_version | regex_replace('^(v)?') }}.{{ prometheus_software_architecture }}.tar.gz"

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
