---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include script_exporter (adhocteam) variable file
  include_vars: exporters/script_exporter_adhocteam.yml

- name: Starting script_exporter (adhocteam) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'script_exporter'
    prometheus_software_env_vars: '{{ prometheus_script_exporter_adhocteam_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_script_exporter_adhocteam_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_script_exporter_adhocteam_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'script_exporter_adhocteam'
    prometheus_software_version: '{{ prometheus_script_exporter_adhocteam_version | default("1.0.2") }}'
    prometheus_software_src_version: '{{ prometheus_script_exporter_adhocteam_src_version | default("v1.0.2") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_script_exporter_adhocteam_jobname | default(prometheus_script_exporter_adhocteam_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus script_exporter (adhocteam), exporter for Script metrics'
    prometheus_software_documentation: 'https://github.com/adhocteam/script_exporter'
    prometheus_software_host: '{{ prometheus_script_exporter_adhocteam_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_script_exporter_adhocteam_port | default(prometheus_script_exporter_adhocteam_default_port) }}'
    prometheus_software_shortname: 'script_exporter'
    # Defined by prometheus_script_exporter_adhocteam_cfgs:
    prometheus_software_opts: []

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/adhocteam/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/adhocteam/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/adhocteam/{{ prometheus_software_shortname }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include tasks to perform individual {{ prometheus_software_name_version }} configurations
  include_tasks: _install_instance.yml
  loop_control:
    loop_var: installer_instance
  loop: '{{ prometheus_script_exporter_adhocteam_cfgs }}'

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
