---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting smokeping_exporter (SuperQ) install
  set_fact:
    prometheus_software_allow_build_test: true
    prometheus_exporter: true
    prometheus_software_author: SuperQ
    prometheus_software_binary_name: smokeping_prober
    prometheus_software_capabilities:
      smokeping_prober:
        - cap_net_raw+ep
    prometheus_software_makefile_make_command: 'go get -d && go build'
    prometheus_software_name: smokeping_exporter_superq
    prometheus_software_description: 'Prometheus smokeping_exporter (superq), exporter for Smokeping metrics'
    prometheus_software_documentation: 'https://github.com/superq/smokeping_exporter'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/smokeping_prober/releases/download/{{ prometheus_software_version }}/\
      smokeping_prober-{{ prometheus_software_version | regex_replace('^(v)?') }}.{{ prometheus_software_architecture }}.tar.gz"

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
