---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting snmp_exporter install
  set_fact:
    prometheus_exporter: true
    prometheus_software_author: prometheus
    prometheus_software_binary_name: snmp_exporter
    prometheus_software_files:
      - 'snmp_exporter'
      - 'snmp.yml'
    prometheus_software_makefile_make_command: make build
    prometheus_software_name: snmp_exporter
    prometheus_software_description: 'Prometheus snmp_exporter, exposes information gathered from SNMP'
    prometheus_software_documentation: 'https://github.com/prometheus/snmp_exporter'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_config_name: '{{ prometheus_software_name }}'
    prometheus_software_opts:
      - '--config.file {{ prometheus_etc_dir }}/snmp_exporter.yml'
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/{{ prometheus_software_name }}/releases/download/{{ prometheus_software_version }}/\
      {{ prometheus_software_name }}-{{ prometheus_software_version | regex_replace('^(v)?') }}.{{ prometheus_software_architecture }}.tar.gz"

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Link {{ prometheus_software_name_version }} configuration file to {{ prometheus_software_install_dir }}/snmp.yml
  become: true
  file:
    src: '{{ prometheus_software_install_dir }}/snmp.yml'
    dest: '{{ prometheus_etc_dir }}/snmp_exporter.yml'
    owner: root
    group: '{{ prometheus_group }}'
    state: link
  notify:
    - Restart Prometheus service
  when: prometheus_snmp_exporter_yml is undefined

- name: Setup {{ prometheus_software_version }} configuration file
  become: true
  copy:
    src: '{{ prometheus_snmp_exporter_yml }}'
    dest: '{{ prometheus_etc_dir }}/snmp_exporter.yml'
    owner: root
    group: '{{ prometheus_group }}'
    mode: 0640
    validate: '{{ prometheus_software_install_dir }}/snmp_exporter --dry-run --config.file %s'
  notify:
    - Restart Prometheus service
  when: prometheus_snmp_exporter_yml is defined

- name: Set {{ prometheus_software_name_version }} validation command facts
  set_fact:
    prometheus_software_validation_command: >-
      {{ prometheus_software_install_dir }}/snmp_exporter --dry-run --config.file {{ prometheus_etc_dir }}/snmp_exporter.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_version }}
  include_tasks: _post_install_cleanup.yml
