---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include sql_exporter (free) variable file
  include_vars: exporters/sql_exporter_free.yml

- name: Starting sql_exporter (free) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'sql_exporter'
    prometheus_software_env_vars: '{{ prometheus_sql_exporter_free_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_sql_exporter_free_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_sql_exporter_free_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'sql_exporter_free'
    prometheus_software_version: '{{ prometheus_sql_exporter_free_version | default("0.4") }}'
    prometheus_software_src_version: '{{ prometheus_sql_exporter_free_src_version | default("0.4") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_sql_exporter_free_jobname | default(prometheus_sql_exporter_free_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus sql_exporter (free), Database agnostic SQL exporter for Prometheus'
    prometheus_software_documentation: 'https://github.com/free/sql_exporter'
    prometheus_software_host: '{{ prometheus_sql_exporter_free_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_sql_exporter_free_port | default(prometheus_sql_exporter_free_default_port) }}'
    prometheus_software_runas: '{{ prometheus_sql_exporter_free_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'sql_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '-web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
      - '-config.file={{ prometheus_etc_dir }}/sql_exporter_free.yml'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_bin_url: 'https://github.com/free/{{ prometheus_software_shortname }}/releases/download/{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/free/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/free/{{ prometheus_software_shortname }}.git'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Setup {{ prometheus_software_name_version }} configuration file
  become: true
  copy:
    content: '{{ prometheus_sql_exporter_free_cfg | default(lookup("file", "../files/sql_exporter_free.yml")) }}'
    dest: '{{ prometheus_etc_dir }}/sql_exporter_free.yml'
    owner: root
    group: root
    mode: '0644'
    backup: true
  register: prometheus_software_cfg

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
