---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting sql_exporter (free) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_author: free
    prometheus_software_binary_name: sql_exporter
    prometheus_software_makefile_make_command: make build
    prometheus_software_name: sql_exporter_free
    prometheus_software_description: 'Prometheus sql_exporter (free), Database agnostic SQL exporter for Prometheus'
    prometheus_software_documentation: 'https://github.com/free/sql_exporter'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '-web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
      - '-config.file={{ prometheus_etc_dir }}/sql_exporter_free.yml'
    prometheus_software_url:
      "https://github.com/{{ prometheus_software_author }}/{{ prometheus_software_binary_name }}/releases/download/{{ prometheus_software_version }}/\
      {{ prometheus_software_binary_name }}-{{ prometheus_software_version | regex_replace('^(v)?') }}.{{ prometheus_software_architecture }}.tar.gz"

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Setup {{ prometheus_software_name_version }} configuration file
  become: true
  copy:
    content: '{{ prometheus_sql_exporter_free_cfg | default(lookup("file", "../files/sql_exporter_free.yml")) }}'
    dest: '{{ prometheus_etc_dir }}/sql_exporter_free.yml'
    owner: root
    group: '{{ prometheus_group }}'
    mode: 0640
    backup: true
  notify:
    - Restart Prometheus service

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
