---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include ssl_exporter (ribbybibby) variable file
  include_vars: exporters/ssl_exporter_ribbybibby.yml

- name: Starting ssl_exporter (ribbybibby) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'ssl_exporter'
    prometheus_software_env_vars: '{{ prometheus_ssl_exporter_ribbybibby_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_ssl_exporter_ribbybibby_extra_opts | default () }}'
    # Do not perform tests, tests only succeed where IPv6 is available
    prometheus_software_fallback_to_build: '{{ prometheus_ssl_exporter_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'ssl_exporter_ribbybibby'
    prometheus_software_version: '{{ prometheus_ssl_exporter_version | default("0.2.0") }}'
    prometheus_software_src_version: '{{ prometheus_ssl_exporter_src_version | default("v0.2.0") }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_ssl_exporter_ribbybibby_jobname | default(prometheus_ssl_exporter_ribbybibby_default_tgroup_jobname) }}'
    prometheus_software_description: 'Prometheus ssl_exporter, SSL Certificate Exporter'
    prometheus_software_documentation: 'https://github.com/ribbybibby/ssl_exporter'
    prometheus_software_host: '{{ prometheus_ssl_exporter_ribbybibby_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_ssl_exporter_ribbybibby_port | default(prometheus_ssl_exporter_ribbybibby_default_port) }}'
    prometheus_software_runas: '{{ prometheus_ssl_exporter_ribbybibby_runas | default(prometheus_user) }}'
    prometheus_software_shortname: 'ssl_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_config_name: '{{ prometheus_software_name }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_bin_url: 'https://github.com/ribbybibby/{{ prometheus_software_shortname }}/releases/download/v{{ prometheus_software_version }}/{{ prometheus_software_shortname }}-{{ prometheus_software_version }}.{{ prometheus_architecture }}.tar.gz'
    prometheus_software_src_dir_suffix: '/src/github.com/ribbybibby/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/ribbybibby/{{ prometheus_software_shortname }}'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
