---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is not defined

- name: Include zookeeper_exporter (infonova) variable file
  include_vars: exporters/zookeeper_exporter_infonova.yml

- name: Starting zookeeper_exporter (infonova) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_binary_name: 'zookeeper_exporter'
    prometheus_software_env_vars: '{{ prometheus_zookeeper_exporter_infonova_env_vars | default({}) }}'
    prometheus_software_extra_opts: '{{ prometheus_zookeeper_exporter_infonova_extra_opts | default() }}'
    prometheus_software_fallback_to_build: '{{ prometheus_zookeeper_exporter_infonova_fallback_to_build | default(prometheus_fallback_to_build) }}'
    prometheus_software_name: 'zookeeper_exporter_infonova'
    prometheus_software_version: '{{ prometheus_zookeeper_exporter_infonova_version | default("1.1") }}'
    prometheus_software_description: 'Prometheus zookeeper_exporter (infonova), exporter of Apache ZooKeeper metrics'
    prometheus_software_documentation: 'https://github.com/infonova/zookeeper_exporter'
    prometheus_software_host: '{{ prometheus_zookeeper_exporter_infonova_host | default("0.0.0.0") }}'
    prometheus_software_port: '{{ prometheus_zookeeper_exporter_infonova_port | default(9114) }}'
    prometheus_software_runas: '{{ prometheus_zookeeper_exporter_infonova_runas | default(prometheus_user) }}'
    prometheus_software_tgroup_jobname: '{{ prometheus_zookeeper_exporter_infonova_jobname | default("zookeeper") }}'
    prometheus_software_shortname: 'zookeeper_exporter'

- name: Set {{ prometheus_software_name }}-{{ prometheus_software_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--web.listen-address={{ prometheus_software_host }}:{{ prometheus_software_port }}'
    prometheus_software_name_version: '{{ prometheus_software_name }}-{{ prometheus_software_version }}'
    prometheus_software_src_dir_suffix: '/src/github.com/infonova/{{ prometheus_software_shortname }}'
    prometheus_software_src_url: 'https://github.com/infonova/{{ prometheus_software_shortname }}/archive/{{ prometheus_software_version }}.tar.gz'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
