---
- block:
  - name: 'Include role mesaguy.prometheus setup task'
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting raspberry_exporter (DerKnerd) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_allow_build_test: true
    prometheus_software_author: DerKnerd
    prometheus_software_binary_name: raspberry_exporter
    prometheus_software_name: raspberry-exporter_DerKnerd
    prometheus_software_description: 'Prometheus raspberry_exporter (DerKnerd), simple wrapper around the vcgencmd executable on Raspberry PIs'
    prometheus_software_documentation: 'https://github.com/DerKnerd/raspberry-exporter'
    prometheus_software_use_prerelease: true

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_opts:
      - '--telemetry.address={{ prometheus_software_host }}:{{ prometheus_software_port }}'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
