---
- block:
  - name: Include role mesaguy.prometheus setup task
    include_tasks: _setup.yml
  when: prometheus_setup_task_executed is undefined

- name: Starting syslog_ng_exporter (brandond) install
  set_fact:
    prometheus_exporter: true
    prometheus_software_allow_build_test: true
    prometheus_software_author: brandond
    prometheus_software_binary_name: syslog_ng_exporter
    prometheus_software_name: syslog_ng_exporter_brandond
    prometheus_software_description: 'Prometheus syslog_ng_exporter for exporting syslog-ng statistics'
    prometheus_software_documentation: 'https://github.com/brandond/syslog_ng_exporter'

- name: Include task to setup {{ prometheus_software_name }} facts
  include_tasks: _setup_software_facts.yml

- name: Set {{ prometheus_software_name_version }} facts
  set_fact:
    prometheus_software_config_name: '{{ prometheus_software_name }}'
    prometheus_software_opts:
      - '--telemetry.address={{ prometheus_software_host }}:{{ prometheus_software_port }}'

- name: Include task to perform installation of {{ prometheus_software_name_version }}
  include_tasks: _install.yml

- name: Include task to setup {{ prometheus_software_name_version }} service
  include_tasks: _service.yml

- name: Include task to perform post install cleanup of {{ prometheus_software_name_version }}
  include_tasks: _post_install_cleanup.yml
